"""Answer domain entity"""

from dataclasses import dataclass
from typing import List, Optional
from enum import Enum
from datetime import datetime


class Confidence(Enum):
    """Answer confidence level"""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


@dataclass
class Answer:
    """
    Answer domain entity
    
    Represents an answer generated by the RAG system.
    """
    text: str
    sources: List['Source']
    confidence: Confidence
    generated_at: datetime
    model_name: str = ""
    temperature: float = 0.0
    
    @classmethod
    def insufficient_context(cls, reason: str) -> 'Answer':
        """Create an answer indicating insufficient context"""
        return cls(
            text=f"I don't have enough information to answer this question. {reason}",
            sources=[],
            confidence=Confidence.INSUFFICIENT_CONTEXT,
            generated_at=datetime.utcnow()
        )
    
    def __str__(self) -> str:
        return self.text
    
    def has_high_confidence(self) -> bool:
        """Check if answer has high confidence"""
        return self.confidence == Confidence.HIGH
    
    def has_sources(self) -> bool:
        """Check if answer has supporting sources"""
        return len(self.sources) > 0

